export const products = [{ProductName:"Overspeed Governor",
    ProductImage:"/products/Overspeed-governer.jpg",
    ProductCategory:"Mechanical Safety Component",
    ProductProp: ["Pulley Dia. - 300mm",
        "Rope Dia. - 6mm - 8mm",
        "Nominal Speed - 0.5 m/s",
        "Tripping Speed - 0.63 m/s"]
    },
    {ProductName:"Safety Clutch",
        ProductImage:"/products/Safety-Clutch.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Action - Instantaneous",
            "For Capacity - Upto 1 Tonne",
            "For Speed - Upto 1.0 m/s",
            "For Rail Size - 9mm, 10mm, 16mm"]
        },
    {ProductName:"Rope Anchorage",
    ProductImage:"/products/Rope-Anchorage.jpg",
    ProductCategory:"Mechanical Safety Component",
    ProductProp: ["Sheetmetal Rope Anchorage",
        "Length - 300mm",
        "For Rope Dia. - 6mm, 8mm",
        "With 7mm spring"]
    },
    {ProductName:"Guide Shoe",
        ProductImage:"/products/Guide-Shoe.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Pulley Dia. - 300mm",
            "For Speed - Upto 0.85 m/s",
            "For Rail Size - 9mm, 10mm",
            ""]
        },
    {ProductName:"Diverter Pulley",
    ProductImage:"/products/Diverter-Pulley.jpg",
    ProductCategory:"Mechanical Safety Component",
    ProductProp: ["High-strength steel construction",
    "Smooth surface for reduced friction and wear",
    "Easy to install and maintain"]
    },
    {ProductName:"Rail Clip",
        ProductImage:"/products/Rail-Clip.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Forged Guide Rail Clip",
            "Finish - Yellow Zinc Plated",
            "Bolt Size - M10x25",
            "For Rail - T45 / T50"]
        },
{ProductName:"Bulldog Clip",
    ProductImage:"/products/Bulldog-Clip.jpg",
    ProductCategory:"Mechanical Safety Component",
    ProductProp: ["Bulldog Clip Casting",
        "Rope Dia. - 5mm - 6.5mm",
        "Tightening Torque - 3.5Nm",
        ""]
    },
{ProductName:"Cable Gripper",
        ProductImage:"/products/Cable-Gripper.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Material - High-strength steel",
            "Capacity - 10,000 lbs.",
            "Dimensions - 12 x 6 x 4",
            ""]
        },    
{ProductName:"Oiler",
        ProductImage:"/products/Oiler.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Forged Guide Rail Clip",
            "Finish - Yellow Zinc Plated",
            "Bolt Size - M10x25",
            "For Rail - T45 / T50"]
        },    
{ProductName:"Bracket",
        ProductImage:"/products/Bracket.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Forged Guide Rail Clip",
            "Finish - Yellow Zinc Plated",
            "Bolt Size - M10x25",
            "For Rail - T45 / T50"]
        },    
{ProductName:"Keys",
        ProductImage:"/products/Keys.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Forged Guide Rail Clip",
            "Finish - Yellow Zinc Plated",
            "Bolt Size - M10x25",
            "For Rail - T45 / T50"]
        },    
{ProductName:"Fastner",
        ProductImage:"/products/Fastner.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["User-friendly design",
            "Easy to install and maintain",
            "",
            ""]
        },    
{ProductName:"Buffer Spring",
        ProductImage:"/products/Buffer-Spring.jpg",
        ProductCategory:"Mechanical Safety Component",
        ProductProp: ["Buffer Spring Without Plate",
            "Coil Dia. - 14mm",
            "Length - 235mm",
            ""]
        },    
{ProductName:"Fuji Drive",
        ProductImage:"/products/Fuji-Drive.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Book type frame up to 15 kW",
            "Applicable for close and open loop application",
            "Contactorless solution compliant to EN 81-1 + A3 and EN 81-20",
            ""]
        },    
{ProductName:"Yaskawa Drive",
        ProductImage:"/products/yaskawa-drive.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Operation - Open Loop / Close Loop",
            "Power - 3.7 to 18kW",
            "Current - 15 Amp",
            "Voltage - 415 VAC"]
        },    
{ProductName:"INVT-Drive",
        ProductImage:"/products/INVT-Drive.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Operation - Open Loop / Close Loop",
            "Power - 3.7 to 18kW",
            "Current - 15 Amp",
            "Voltage - 415 VAC"]
        },    
{ProductName:"Monarch Drive",
        ProductImage:"/products/Monarch-Drive.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Standard 8 floor full collecve, expansion opon 12 floor full collecve.",
            "Operation - Close loop + Parallal communication.",
            "Power - 3.7kw to 18.5kw.",
            ""]
        },    
{ProductName:"Fuji Nova Controller",
        ProductImage:"/products/Fuji-Nova-Controller.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Suitable for 2 speed , hydraulic and VVVF Lift.",
            "Communication mode - Parallal.",
            "Operating voltage - 24VDC/12VDC",
            "Cabinet Size -1230x540x250."]
        },    
{ProductName:"Yaskawa Controller",
        ProductImage:"/products/Yaskawa-controller.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Motor Capacity - 7.5kw to 18.5kw and above.",
            "Communication mode - Parallal/Complete Serial/Car Serial",
            "Operating voltage - 24VDC",
            ""]
        },    
{ProductName:"INVT Controller",
        ProductImage:"/products/Yaskawa-controller.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Compatible with geared and gearless close loop and geared open loop",
            "Motor Capacity - 4kw to 11kw",
            "Communication mode - Parallal",
            ""]
        },    
{ProductName:"Monarch Controller",
        ProductImage:"/products/Yaskawa-controller.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Operting Voltage-323v to 528v",
            "Motor Capcity- 3.7kw to 5.5 kw",
            "Cabient Size- 1800*400*265",
            "ommuniction Mode-parallel / Serial"]
        },    
{ProductName:"Vega Controller",
        ProductImage:"/products/.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Cooming soon",
            "",
            "",
            ""]
        },    
{ProductName:"Controller card",
        ProductImage:"/products/Controller-card.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Suitable for VVVF, Hydraulic & 2-Speed lift control.",
            "Communication : Parallel.",
            "Floor indicator : Seven segment, Binary & Gray. View Product",
            ""]
        },    
{ProductName:"UPS With Batteries",
        ProductImage:"/products/UPS-With-Batteries.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["True Online UPS with Triple Conversion",
            "Wide Input Voltage Range",
            "Built-in OVCD for High Voltage Protection",
            "Active Input Power Factor Corrector"]
        },    
{ProductName:"Harness",
        ProductImage:"/products/.jpg",
        ProductCategory:"Controller and Drives",
        ProductProp: ["Plug N play Harness View Product",
            "",
            "",
            ""]
        },    
{ProductName:"Switch Gear and Relay",
        ProductImage:"/products/Switch-Gear.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Includes blade style terminals",
            "Offers 7 or 10 A contact ratings",
            "Includes standard ON/OFF flag indicator",
            ""]
        },    
{ProductName:"Transformer and Smps",
        ProductImage:"/products/Transformer.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Effective isolation from the noisy power lines",
            "Electrostatic shielding and protections high galvanic isolation",
            "Suppressions of common mode and transverse mode noise",
            ""]
        },    
{ProductName:"Cables & Wires",
        ProductImage:"/products/Cables.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Brand - Rolyflex.",
            "Conductor Type - Flexible Copper",
            "Core - 12core",
            "Voltage Grade - 200V TO 300V"]
        },    
{ProductName:"DBR",
        ProductImage:"/products/DBR.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["POWER RATING - 60W TO 4000W.",
            "OHMIC VALUE - 1U TO 10KU.",
            "Temprature Co-efficient - < 150 ppm / ºC",
            "Overload Withstanding 10X Power for 5 Secs"]
        },    
{ProductName:"Dindril",
        ProductImage:"/products/Dindril.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Din Rail 35mm X 7mm Thickness 1mm",
            "Slotted (Weight 620 Gms App.) and Unslotted (Weight 666 Gms)",
            "2 Meters/ 6’ 6” Long Zinc-Bichromate",
            "Cold Rolled Electrolitically Plated Steel"]
        },    
{ProductName:"PVC Truff",
        ProductImage:"/products/PVC-Truff.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Coming soon",
            "",
            "",
            ""]
        },    
{ProductName:"Door Sensor",
        ProductImage:"/products/Door-Sensor.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Light Immunity >100000 LUX",
            "IP54 Rated",
            "Low Power Consumption",
            "Comes with 4 mtr Cable and Power Supply Box"]
        },    
{ProductName:"Overload Sensor",
        ProductImage:"/products/Overload-Sensor.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["2 programmable alarms: Full load & Overload.",
            "Integrated display to show weight values up to 999 KG.",
            "Automatic calibration using the wire rope diameter, meaning no need for test weights",
            "Universal rope clamps for all types of rope distribution"]
        },    
{ProductName:"Inspection and Junction Box",
        ProductImage:"/products/Inspection.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Up, Down & Common Push Button",
            "Selector Switch (Inspection / Normal)",
            "Mushroom Emergency Stop",
            "Power Output"]
        },    
{ProductName:"Fireman and Emergency",
        ProductImage:"/products/Fireman.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Material - Mild Steel",
            "Shape - Rectangle",
            "Type - Emergency Alarm",
            "Use - Elevator/Lift"]
        },    
{ProductName:"Limit Switch",
        ProductImage:"/products/Limit-Switch.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Current Rating - 6-10A",
            "switch Type - Limit Switch",
            "Volatge - 250-380 VAC",
            "Operating Temperature - 10-60 Degree C View Product"]
        },    
{ProductName:"Reed Switch",
        ProductImage:"/products/Reed-Switch.jpg",
        ProductCategory:"Electrical Components",
        ProductProp: ["Current Rating (Amps) - 150A",
            "Power/Voltage - 110-220 Volt",
            "Material/Body - Plastic",
            "Safe to use"]
        },    
{ProductName:"REVA",
        ProductImage:"/products/REVA.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - Surface Mounted 970X190X16mm",
            "Standard Finish - SS Hairline",
            "Button - Round with Braille & Blue colour",
            "Display - 7 Segment, Dot Matrix | Display Color - Blue"]
        },    
{ProductName:"ROYAL COP",
        ProductImage:"/products/ROYAL.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - Surface Mounted 970x190x20mm",
            "Button - Oval with Braille & Red colour",
            "Available Volatage - 12V & 24V",
            "Display - 7 Segment, Dot Matrix | Display Color - Red"]
        },    
{ProductName:"NEXA",
        ProductImage:"/products/NEXA.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Scalable architecture",
            "Wide range of features and options",
            "Reliable and robust design",
            "Comprehensive warranty"]
        },    
{ProductName:"ORCA",
        ProductImage:"/products/ORCA.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Pad Color - White,Black",
            "Button - MAS Touch Button",
            "Color Glow - White, Red, Blue, Yellow, Green",
            "Display - 7 Segment, Dot Matrix, TFT | Display color: Red, Blue"]
        },    
{ProductName:"BCG",
        ProductImage:"/products/BCG.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Acrylic - Black",
            "Button - BST Round",
            "Voltage - 12V, 24V",
            "Display - 7 Segment | Display Color - Red"]
        },    
{ProductName:"INNOVA",
        ProductImage:"/products/INNOVA.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - Surface Mounted 970X190X16mm",
            "Standard Finish - SS Black Hairlinne",
            "Button - Square with Braille & Red colour",
            "Available Volatage - 12V & 24V"]
        },    
{ProductName:"VISION",
        ProductImage:"/products/VISION.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - Wall Mounted 1300X215X62mm",
            "Standard Finish - Black , White",
            "Button - Capacitive feather touch",
            "Available Volatage - 12V"]
        },    
{ProductName:"GALAXY",
        ProductImage:"/products/GALAXY.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - Surface Mounted 1000X179X16mm",
            "Standard Finish - ss sandblast",
            "Button - Square with Braille & Red colour",
            "Available Volatage -12 & 24V"]
        },    
{ProductName:"HANDRAIL COP",
        ProductImage:"/products/HANDRAIL-COP.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Available in Mirror, Gold",
            "Dot matrix Display",
            "Button - Square with Braille & Red colour",
            "Available Volatage -24V"]
        },    
{ProductName:"EPAD",
        ProductImage:"/products/EPAD.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["768(W)×1024(H) 9.7 inch",
            "Vertical interface | Capacitive screen",
            "TFT VGA Color display",
            "Provision for keypad access control"]
        },    
{ProductName:"PUSH BUTTONS",
        ProductImage:"/products/PUSH-BUTTONS1.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["MAS OVAL",
            "Type - Surface Mounted 970X190X16mm",
            "Button Color- Silver,Gold",
            "Glow Color - Red, Blue"]
        },    
{ProductName:"PUSH BUTTONS",
        ProductImage:"/products/PUSH-BUTTONS2.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["ROUND BLUE",
            "Type - MAS Oval",
            "Button Color- Silver",
            "Glow Color -Blue"]
        },    
{ProductName:"SQUARE",
        ProductImage:"/products/PUSH-BUTTONS3.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - Red",
            "Voltage - 12V, 24V",
            "Button Color- Silver",
            "Glow Color -Red"]
        },    
{ProductName:"ROUND SLIM",
        ProductImage:"/products/PUSH-BUTTONS4.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Voltage - 12V, 24V",
            "Type - Round slim",
            "Button Color- Silver",
            "Glow Color -Red"]
        },    
{ProductName:"AVOX",
        ProductImage:"/products/PUSH-BUTTONS5.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type - AVOX",
            "Button Color- Silver",
            "Voltage - 12V, 24V",
            "Glow Color -Blue, Red"]
        },    
{ProductName:"MAS Touch Button",
        ProductImage:"/products/PUSH-BUTTONS6.jpg",
        ProductCategory:"COP & LOP",
        ProductProp: ["Type -MAS Touch Button",
            "Voltage - 24V",
            "Glow Color -white , Red",
        ""]
        },
{ProductName:"Mild Steel Powder Coated Cabin",
        ProductImage:"/products/sub-cabin.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Stainless steel hairline finish cabins are a popular choice for their sleek and modern look. They are also very durable and do not require painting, making them a low-maintenance option.",
            "The center panel on the rear side of the cabin is made from stainless steel mirror finish sheets. This provides a luxurious and elegant look, and it is also much more durable than glass mirrors. Stainless steel mirrors are also shatter-resistant, making them a safer option for high-traffic areas."]
        },
{ProductName:"Stainless Steel Hairline Finish Cabin",
        ProductImage:"/products/sub-cabin2.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Stainless steel hairline finish cabins offer a sleek, modern look that is also very durable. They do not require painting, making them a low-maintenance option. The center panel on the rear side of the cabin is made from stainless steel mirror finish sheets, which provides a luxurious and elegant look. Stainless steel mirrors are also much more durable than glass mirrors and are shatter-resistant, making them a safer option for high-traffic areas."]
        },
{ProductName:"Stainless Steel Designer Finish Cabin",
        ProductImage:"/products/sub-cabin3.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Stainless steel designer finish cabins are the most luxurious and elegant option available. The designs on the cabin are created by etching, which is a process that uses acid to create a permanent pattern on the metal. This process is very durable and will last for the life of the cabin."]
        },
{ProductName:"Panaromic / Capsule Type Cabin",
        ProductImage:"/products/sub-cabin4.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Panoramic or capsule elevators are a type of elevator that has large windows on all sides, allowing passengers to enjoy a view of the outside while they travel. These elevators are often used in high-rise buildings, hotels, and other commercial and public spaces. Panoramic elevators offer a number of advantages over traditional elevators. They provide passengers with a sense of openness and spaciousness, and they can help to create a more inviting and luxurious atmosphere. They can also help to improve the overall aesthetics of a building."]
        },
{ProductName:"Carframe",
        ProductImage:"/products/carframe.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Made of high-quality steel",
            "Durable and long-lasting",
            "Easy to install and maintain"]
        },
{ProductName:"Round Handrail",
        ProductImage:"/products/handrails.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Available in Golden, Silver & Bronze Mirror",
            "Available in Sizes from 600 mm to 1300 mm",
            "Round Pipe Diameter - 38mm"]
        },
{ProductName:"Bow Type Handrail",
        ProductImage:"/products/handrials2.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Available in Golden, Silver & Bronze Mirror",
            "Available in Sizes from 600 mm to 1300 mm",
            "Pipe Diameter - 38mm"]
        },
{ProductName:"1W Round LED Panel",
        ProductImage:"/products/1W.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Available in White and Warm White Shade",
            "Cut out Size - 32 mm to 35 mm",
            "Power Factor > 0.9",
        "Luminous Flux - 130 lm",
    "Aluminium body with 2 years of service life"]
        },
{ProductName:"3W Round LED Spot Light",
        ProductImage:"/products/3W.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Available in White and Warm White Shade",
            "Cut Out Size - 55mm",
            "Power Factor > 0.9",
        "Operating Voltage - 90 to 300V",
    "Luminous Flux - 390 lm",
"Aluminium body with 2 years of service life"]
        },
{ProductName:"4W Round LED Panel",
        ProductImage:"/products/4W.webp",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Available in White and Warm White Shade",
            "Cut Out Size - 70mm to 72mm",
            "Power Factor > 0.9",
        "Operating Voltage - 90 to 300V",
    "Luminous Flux - 520 lm",
    "Aluminium body with 2 years of service life"]
        },
{ProductName:"3W Round LED Spot Light",
        ProductImage:"/products/Rexnord.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Diamensions - Ø 220 x 60 mm",
            "Ball Bearing 230V & 60W input power",
            "Plastic Impeller for light in weight & safety purpose"]
        },
{ProductName:"Machine Mounting",
        ProductImage:"/products/Machine-Mounting.jpg",
        ProductCategory:"Cabins and car frames",
        ProductProp: ["Secures the elevator machine to the elevator shaft",
            "Helps to ensure the safety of passengers",
            "Reduces the risk of accidents",
        "Increases the lifespan of the elevator"]
        },
{ProductName:"PVC Flooring AEZ-148",
        ProductImage:"/products/PVC.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-149",
        ProductImage:"/products/PVC1.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-151",
        ProductImage:"/products/PVC2.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-152",
        ProductImage:"/products/PVC3.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-153",
        ProductImage:"/products/PVC4.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-154",
        ProductImage:"/products/PVC5.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-150",
        ProductImage:"/products/PVC0.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"PVC Flooring AEZ-155",
        ProductImage:"/products/PVC6.jpg",
        ProductCategory:"Cabin Flooring",
        ProductProp: ["Material Type - PVC",
            "Available in two sizes outside area 152 x 162 cm & 120 x 120 cm",
            "Thickness - 2 mm"]
        },
{ProductName:"MAC-FP",
        ProductImage:"/products/MA.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Plug and play.",
            "To be store 200 finger print",
            "size: 45mmX65mm",
        "voltage: 24V (DC)"]
        },
{ProductName:"MAC-KP",
        ProductImage:"/products/MA1.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Plug and play.",
            "Easy to connect",
            "size: 45mmX65mm",
        "voltage: 24V (DC)"]
        },
{ProductName:"MAC-RF",
        ProductImage:"/products/MA2.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Plug and play.",
            "80 RFID token/card along one master user",
            "size: 45mmX65mm",
        "voltage: 24V (DC)"]
        },
{ProductName:"Door open bell",
        ProductImage:"/products/door.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Input Voltage - 12VDC / 24VDC.",
            "Speaker - 8 Ohm / 20W",
            "Easy volume control"]
        },
{ProductName:"MLA",
        ProductImage:"/products/MLA.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Floor announcement in 2 different languages",
            "Input Voltage - 12VDC / 24VDC",
            "Input Mode - Seven Segment / Binary / Binary 1 / Gray"]
        },
{ProductName:"SEVEN SEGMENT RED",
        ProductImage:"/products/",
        ProductCategory:"Electronic Components",
        ProductProp: ["7 Segment COP Display Board",
            "Input Voltage - 12VDC / 24VDC",
            "Common +ve"]
        },
{ProductName:"SEVEN SEGMENT BLUE",
        ProductImage:"/products/",
        ProductCategory:"Electronic Components",
        ProductProp: ["7 Segment COP Display Board",
            "Input Voltage - 12VDC / 24VDC",
            "Common +ve"]
        },
{ProductName:"MEL2",
        ProductImage:"/products/MEL2.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Input voltage - 6V / 12V",
            "White LED lighting",
            "Silver crome plated ring"]
        },
{ProductName:"MEL3",
        ProductImage:"/products/MEL3.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Input voltage - 12V / 24V",
            "White SMD LED lighting",
            "Slim design"]
        },
{ProductName:"Battery Backup",
        ProductImage:"/products/Battery-Backup.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["High-quality batteries that provide reliable power in the event of a power outage",
            "Durable construction that can withstand the harsh environment of an elevator shaft",
            "Easy to install and maintain",
        "Backed by our industry-leading warranty"]
        },
{ProductName:"MCBS",
        ProductImage:"/products/MCBS.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Binary to seven segment conversion",
            "Input Voltage - 12VDC / 24VDC",
            "Easy mounting on Din-Rail"]
        },
        
{ProductName:"MCDB",
        ProductImage:"/products/MCDB.jpg",
        ProductCategory:"Electronic Components",
        ProductProp: ["Decimal to binary conversion Board",
            "Input Voltage - 12VDC / 24VDC",
            "Easy mounting on Din-Rail",
        "PCB mount screw terminal block connectors"]
        },
{ProductName:"Montanari M67",
        ProductImage:"/products/Geared.jpg",
        ProductCategory:"Machines",
        ProductProp: ["Capacity - 6 Passenger (408 Kg)",
            "Gear Ratio - 1/37",
            "Speed - 1 m/s",
        "Output / Current - 4 kW / 9 A",
    "Available in Sheave Dia.520mm x Dia. 10mm x 3 nos & Dia.520mm x Dia. 13mm x 3 no"]
        },
{ProductName:"Montanari M77",
        ProductImage:"/products/Geared1.jpg",
        ProductCategory:"Machines",
        ProductProp: ["Capacity - 8 Passenger (544 Kg)",
            "Gear Ratio - 1/55",
            "Speed - 0.63 m/s",
        "Output / Current - 5.5 kW / 14.2 A",
    "Available in Sheave - Dia.520mm x Dia. 10mm x 4 nos & Dia.520mm x Dia. 13mm x 3 nos"]
        },
{ProductName:"KDS WR-408-100-H",
        ProductImage:"/products/KDS.jpg",
        ProductCategory:"Machines",
        ProductProp: ["Capacity - 6 Passenger (408 Kg)",
            "Speed - 1.0 m/s",
            "Output / Current - 2.4kW / 7.6A",
        "Sheave - Dia.320mm x Dia. 8mm x 4 nos"]
        },
{ProductName:"KDS WR-544-100-H",
        ProductImage:"/products/KDS1.jpg",
        ProductCategory:"Machines",
        ProductProp: ["Capacity - 8 Passenger (544 Kg)",
            "Speed - 1.0 m/s",
            "Output / Current - 3.2 kW / 9.7 A",
        "Sheave - Dia.320mm x Dia. 8mm x 4 nos"]
        },
{ProductName:"Hydraulic Kits",
        ProductImage:"/products/hydraulic.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["High-quality components that are designed to withstand the harsh environment of an elevator shaft",
            "Reliable performance that can be counted on to keep your elevator running smoothly",
            "Efficient operation that can save you money on your energy bills",
        "Long lifespan that means you won't have to replace your kit anytime soon"]
        },
{ProductName:"HC - Homelift",
        ProductImage:"/products/HC.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Cylinder with overall dimension for homelift Applicaton",
            "Available in 50,60 & 70 mm diameter with thicknes upto 12 mm",
            "Capacity - 250 Kgs",
        "Travel Distance - 3500 mm"]
        },
{ProductName:"CT - Telescopic",
        ProductImage:"/products/CT.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Available the Homelift version with reduced size",
            "Multistage synchronized telescopic",
            "Suitable for panoramic installations",
        "Standard plate included"]
        },
{ProductName:"CS - Slim",
        ProductImage:"/products/cs.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Cylinder with overall dimension for homelift Applicaton",
            "Available 80, 90, 100, 110 diameters",
            "Capacity - 480 kgs",
        "Travel Distance - 6500 mm"]
        },
{ProductName:"C97 - Standard",
        ProductImage:"/products/C97.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Cylinder with overall dimension for homelift Applicaton",
            "Available from 80 to 230 mm diameter",
            "Squre flange joint for an easier assembly",
        "Rupture valve can be easily assembled in non-standard position"]
        },
{ProductName:"HOMELIFT HC PUMP UNIT (HYDRAULIC PUMP UNIT WITH SUBMERGED MOTOR)",
        ProductImage:"/products/HOMELIFT.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["More consecutive travel than the air cooled motor",
            "Available between 1 (up to 27 l/min) or 2 speed, with single or three phase 50/60 Hz submerged motors",
            "Capacity - 250 Kgs",
        "Maximum low noise as the motor is submerged"]
        },
{ProductName:"HEVOS HE Pump Unit",
        ProductImage:"/products/HEVOS.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Electronic Control board with Self-learn mode and Wifi Conection",
            "Control Panel interface with CANopen (1 Master board + 7 slave max)",
            "Do not need incoder in the shaft",
        "Working Pressure Range - 10 -45 Bar"]
        },
{ProductName:"HOMELIFT HC PUMP UNIT WITH AIR COOLED & ECO DRY SOLUTION",
        ProductImage:"/products/HOMELIFT-HC.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Low energy consumption and low quantity of oil",
            "Easy access to the external motor",
            "Available between 1 (up to 27 l/min) or 2 speed, with single or three phase 50/60 Hz dry electrical motors"]
        },
{ProductName:"HI Pump Unit",
        ProductImage:"/products/HI.jpg",
        ProductCategory:"Hydraulic Systems",
        ProductProp: ["Precise floor approach independent on the load and temperature",
            "Up to 1 m/s speed",
            "Inspection and re-levelling speed are adjustable",
        "Connectable with remote control system"]
        },
{ProductName:"Guide Rail",
        ProductImage:"/products/Guide.jpg",
        ProductCategory:"Shaft Component",
        ProductProp: ["Rail Size - T45x45x5mm"]},
{ProductName:"Wire Rope",
        ProductImage:"/products/Wire.jpg",
        ProductCategory:"Shaft Component",
        ProductProp: ["Rope Diameter - 8mm"]
        },
{ProductName:"Flat cable",
        ProductImage:"/products/Flat.jpg",
        ProductCategory:"Shaft Component",
        ProductProp: ["Material - Copper",
            "Dimensions - 100mm x 200mm",
            "Weight - 10g",
        "Current - 1A",
    "Power - 220W"]
        },
{ProductName:"Gate Lock RCam",
        ProductImage:"/products/Gate-Lock-Rcam.jpg",
        ProductCategory:"Shaft Component",
        ProductProp: ["Material - Steel",
            "Dimensions - 100mm x 200mm",
            "Weight - 100g",
        "voltage: 220V",
    "Current - 1A",
"power: 220W"]
        },
{ProductName:"Compensation Chain",
        ProductImage:"/products/compensation-chain.jpg",
        ProductCategory:"Shaft Component",
        ProductProp: ["Material - Steel",
            "Dimensions - 100mm x 200mm",
            "Weight - 100g",
        "voltage: 220V",
    "Current - 1A",
"power: 220W"]
        },
        
    ]